spring:
  application:
    name: auth-service

keycloak:
  server:
    url: http://localhost:8080
  realm: filestorage
  clientId: filestorage-auth-client
  clientSecret: k2OUn8hmu7zaTmADJARAceYNbsF3rFWj


authorization:
  redirect:
    uri: https://localhost:8000/api/v1/auth/callback

server:
  port: 8001
